### ISSUE TITLE
Child window throws missing method exception

### ISSUE THREAD

**Issue by cmpbedes** [texus/TGUI.Net#3]
Hello,

I've encountered the following error when using ChildWindow and i hit the close button:
```
System.MissingMethodException: 'Constructor on type 'TGUI.GuiContainer' not found.'
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at TGUI.Widget.get_Parent()
   at TGUI.ChildWindow.ProcessClosedSignal()
   at TGUI.Gui.tguiGui_handleEvent(IntPtr cPointer, Event ev)
   at TGUI.Gui.OnMouseReleased(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at SFML.Window.Window.CallEventHandler(Event e)
   at SFML.Window.Window.DispatchEvents()
```
How i construct the child window:
```
var childWindow = new ChildWindow("TestTitle")
{
    Position = new Vector2f(10, 10),
    Size = new Vector2f(480, 480)
};
```

Screenshot of title bar from my child window showing the close button

![image](https://user-images.githubusercontent.com/12137479/42620616-59e515e2-85b3-11e8-8ed7-4ed65bca4c48.png)

Thanks

**Comment by texus** [comment]
I managed to reproduce the crash and I'll try to solve it as soon as possible.
For me the close button displays the `✕` correctly, but I should check if this is maybe a windows specific issue because I'm testing it on linux.

**Comment by texus** [comment]
The MissingMethodException has been fixed.

I can reproduce the weird text on top of the close button on windows, so I'll look into that this weekend.

**Comment by cmpbedes** [comment]
That's great, I'm glad I could help, it's a great library I'm really enjoying using it

**Comment by texus** [comment]
It turns out that the issue came from the c++ TGUI library which had the UTF-8 characters directly in the source file. I guess the pc building the .Net libs didn't use the same file encoding. I just represented the characters as hexadecimals and now the issue seems to be solved (in TGUI.Net 0.8.0.5-beta).
I'm glad you enjoy it. Thanks for reporting this and making the library even better.
